export type Screen = 'start' | 'intro' | 'question' | 'developer-wish' | 'narrative' | 'end-narrative' | 'end' | 'final-processing' | 'identity-confirmed' | 'gift-unlocked' | 'album' | 'album-closing' | 'letter' | 'final-menu'
export type FinalStage = 'none' | 'processing-997' | 'processing-998' | 'hang' | 'hang-complaint' | 'intervention-first' | 'intervention-push' | 'complete-100' | 'identity-confirmed' | 'gift-unlocked' | 'album' | 'album-closing' | 'letter' | 'final-menu'
export type NarrativeKind = 'malecon' | 'it-takes-two' | 'medical-intro' | 'medical-alert'
export type BriitPose = 'idle' | 'talking' | 'thinking' | 'pointing' | 'happy' | 'concerned' | 'determined' | 'alert' | 'surprised' | 'waiting'
export type AnswerValue = string | number | string[] | { option?: string; customText?: string; selected?: string[] }
export type AnswerMap = Record<string, AnswerValue>
export type QuestionType = 'text' | 'textarea' | 'choice' | 'slider' | 'zodiac' | 'color-choice' | 'multi-text' | 'multi-select' | 'medical-impossible-case' | 'biometric-scan' | 'forbidden-button'
export type Phase = 'VERIFICACIÓN DE IDENTIDAD' | 'ANÁLISIS DE PERSONALIDAD' | 'EXAMEN CONDUCTUAL' | 'EVALUACIÓN MÉDICA' | 'PRUEBAS ALTAMENTE CIENTÍFICAS' | 'ACTIVIDAD SOSPECHOSA' | 'VERIFICACIÓN FINAL'
export interface DialogueBeat { text: string; pose: BriitPose }
export interface Reaction { text: string; pose: BriitPose; action?: 'next' | 'retry' | 'wish-next' | 'q22'; beats?: DialogueBeat[] }
export interface QuestionDefinition { id: string; number: number; type: QuestionType; phase: Phase; prompt: string; helperText?: string; label?: string; options?: string[]; briitPose: BriitPose; progressPercent: number; submitLabel?: string; skipLabel?: string; sliderLabels?: { left: string; right: string }; fields?: string[]; getReaction: (answer: AnswerValue, skipped?: boolean) => Reaction }
export interface GameState { screen: Screen; questionIndex: number; answers: AnswerMap; wishes: { first: string; second: string; third: string }; progress: number; phase: Phase | null; phaseIntrosCompleted: { medical: boolean }; reaction: Reaction | null; reactionBeat: number; q22Stage: 'idle' | 'intro' | 'overflow' | 'final'; q22OverflowReady: boolean; q26IntroSeen: boolean; q26IntroBeat: number | null; activeWish: 1 | 2 | 3 | null; wishIntroBeat: number | null; narrative: { kind: NarrativeKind; beat: number } | null; endBeat: number; q28Alert: boolean; finalStage: FinalStage; finalBeat: number; albumBeat: number; introGiftStarted: boolean; introGiftBeat: number; questionnaireCompleted: boolean; briefCompleted: boolean; submissionSessionId: string | null; submissionPending: boolean; answersSubmitted: boolean }
